### ISSUE TITLE
Geocorrection of transition layer creates empty grid cells 

### ISSUE THREAD

**Issue by fleurhierink** [AgrDataSci/gdistance#9] opened 2021-07-17 16:27 UTC
Dear reader, 

When geocorrecting a transition layer (projection = +proj=utm +zone=51 +datum=WGS84 +units=m +no_defs) the output creates a diagonal pattern with empty cells (see examples below). 

**I run the following code:**
```
# libraries
library(gdistance)
library(sf)
library(raster)
library(sp)
library(rgdal)

# load data
points <- readOGR("data/processed/points.shp")
friction_layer <- raster("data/processed/landcover_friction.tif")

# make transition layer
transition <- transition(friction_layer, function(x) 1/mean(x), 8
transition_gc <- geoCorrection(transition)
```  

**And this is the output:**
![image](https://user-images.githubusercontent.com/51711013/126043291-3d2d19ff-5e0a-40e9-a981-51c10d5166d9.png)

![image](https://user-images.githubusercontent.com/51711013/126043318-1f862419-aec5-4ede-bd0c-532f806d3dfd.png)

Is there anything I'm missing or I should code differently? Or is this a bug in the library?  

Thank you in advance for any help you might have :)

**Comment by andrewmarx** [comment] 2023-10-02 22:14
I'm going ahead and closing this since it's so old. Should you ever return to it and have the same issue after updating gdistance, raster, and terra, feel free to reopen it and please attach example rasters that reproduce the problem

**Closed as completed by andrewmarx** 2023-10-02 22:14 UTC
